# Generated by Django 5.2.5 on 2025-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='exchange',
            field=models.CharField(default='NSE', max_length=20),
        ),
        migrations.AddField(
            model_name='holding',
            name='gain_loss_inr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holding',
            name='gain_loss_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holding',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='market_cap',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
