# Generated by Django 5.2.5 on 2025-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_holding_exchange_holding_gain_loss_inr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='exchange',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='gain_loss_inr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='gain_loss_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
