# Generated by Django 5.2.5 on 2025-08-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_holding_exchange_alter_holding_gain_loss_inr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='value',
            new_name='value_inr',
        ),
    ]
