# Generated by Django 5.2.5 on 2025-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_value_holding_value_inr'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('portfolio_value', models.FloatField()),
                ('nifty50_value', models.FloatField()),
                ('gold_value', models.FloatField()),
            ],
        ),
    ]
